#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Viola.Resource", IsApplication=true)]

namespace Viola
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Viola.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Viola.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Viola.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListBackground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ListFound = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListLookup = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ListUndone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int StartIconViola = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ViolaBtnDraw = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001e
			public const int CallSlipImage = 2131165214;
			
			// aapt resource value: 0x7f070020
			public const int CallSlipStatus = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int CallSlipTitle = 2131165215;
			
			// aapt resource value: 0x7f07002b
			public const int MainMenu = 2131165227;
			
			// aapt resource value: 0x7f070023
			public const int RaportBackBtn = 2131165219;
			
			// aapt resource value: 0x7f070014
			public const int barcodeButton = 2131165204;
			
			// aapt resource value: 0x7f070028
			public const int buttonLogin = 2131165224;
			
			// aapt resource value: 0x7f07002d
			public const int callLogOutButton = 2131165229;
			
			// aapt resource value: 0x7f070011
			public const int chipButton = 2131165201;
			
			// aapt resource value: 0x7f07002a
			public const int contentFrame = 2131165226;
			
			// aapt resource value: 0x7f070026
			public const int editTextPassword = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int editTextPhoneCommunicationUrl = 2131165223;
			
			// aapt resource value: 0x7f070024
			public const int editTextUserId = 2131165220;
			
			// aapt resource value: 0x7f07002e
			public const int fetchCallSlipsButton = 2131165230;
			
			// aapt resource value: 0x7f070019
			public const int fetchCallSlipsFromFileButton = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int fetchNewCallSlipsButton = 2131165213;
			
			// aapt resource value: 0x7f070013
			public const int foundButton = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int image1 = 2131165206;
			
			// aapt resource value: 0x7f070029
			public const int myList = 2131165225;
			
			// aapt resource value: 0x7f070012
			public const int needsLookup = 2131165202;
			
			// aapt resource value: 0x7f070002
			public const int nextButton = 2131165186;
			
			// aapt resource value: 0x7f070021
			public const int poster_alla = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int poster_ej_alla = 2131165218;
			
			// aapt resource value: 0x7f070000
			public const int previousButton = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int printButton = 2131165205;
			
			// aapt resource value: 0x7f07002f
			public const int reportFetchButton = 2131165231;
			
			// aapt resource value: 0x7f070003
			public const int scrollView1 = 2131165187;
			
			// aapt resource value: 0x7f07002c
			public const int submenu = 2131165228;
			
			// aapt resource value: 0x7f070025
			public const int textView1 = 2131165221;
			
			// aapt resource value: 0x7f070017
			public const int textView10 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int textView11 = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int textView12 = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int textView13 = 2131165211;
			
			// aapt resource value: 0x7f070004
			public const int textView2 = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int textView3 = 2131165196;
			
			// aapt resource value: 0x7f07001c
			public const int textView4 = 2131165212;
			
			// aapt resource value: 0x7f070008
			public const int textViewSeriesStatement = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textViewYvi = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int twArea = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int twBarCode = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int twCSnote = 2131165199;
			
			// aapt resource value: 0x7f070006
			public const int twCallNumber = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int twDeliveryType = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int twNumberOfDone = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int twSeriesStatement = 2131165193;
			
			// aapt resource value: 0x7f070010
			public const int twStatus = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int twTitle = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int twYearVolumeIssue = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CallSlipDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CallSlipFetchingRequest = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CallSlipShort = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CalSlipRapportera = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscanneractivitylayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int zxingscannerfragmentlayout = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040018
			public const int ExternalNote = 2130968600;
			
			// aapt resource value: 0x7f04001c
			public const int Ja = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int RaportBack = 2130968612;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f04000d
			public const int area = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int back = 2130968592;
			
			// aapt resource value: 0x7f040019
			public const int barcode = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int callSlipDetails = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int callnumber = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int fetchNewCallSlips = 2130968607;
			
			// aapt resource value: 0x7f04001a
			public const int fetchcallslips = 2130968602;
			
			// aapt resource value: 0x7f040015
			public const int found = 2130968597;
			
			// aapt resource value: 0x7f04000a
			public const int loginbutton = 2130968586;
			
			// aapt resource value: 0x7f04001b
			public const int message = 2130968603;
			
			// aapt resource value: 0x7f040020
			public const int missingInternetConnection = 2130968608;
			
			// aapt resource value: 0x7f040013
			public const int needslookup = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int next = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int password = 2130968585;
			
			// aapt resource value: 0x7f040022
			public const int phoneCommunicationUrl = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int phoneCommunicationUrlText = 2130968611;
			
			// aapt resource value: 0x7f040014
			public const int previous = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int printslip = 2130968580;
			
			// aapt resource value: 0x7f040021
			public const int printslipmodel = 2130968609;
			
			// aapt resource value: 0x7f040012
			public const int readBarcode = 2130968594;
			
			// aapt resource value: 0x7f04000b
			public const int readtag = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int releaseunfetcheddialoguemessage = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int releaseunfetcheddialoguetitle = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int reportcollecting = 2130968576;
			
			// aapt resource value: 0x7f04000e
			public const int seriesStatement = 2130968590;
			
			// aapt resource value: 0x7f040016
			public const int status = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int title = 2130968588;
			
			// aapt resource value: 0x7f040025
			public const int treatedposterAll = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int treatedposterNotAll = 2130968614;
			
			// aapt resource value: 0x7f040017
			public const int type = 2130968599;
			
			// aapt resource value: 0x7f040008
			public const int username = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int viola = 2130968583;
			
			// aapt resource value: 0x7f04001d
			public const int wrap = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int wrapDash = 2130968606;
			
			// aapt resource value: 0x7f040001
			public const int yearvolumeissue = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int MainBackground = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ViolaBtn = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ViolaBtnSmall = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
