#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Viola.Resource", IsApplication=true)]

namespace Viola
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Viola.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Viola.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Viola.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListBackground = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ListFound = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ListLookup = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ListUndone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int splash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int StartIconViola = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ViolaBtnDraw = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int CallSlipImage = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int CallSlipStatus = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int CallSlipTitle = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int LoginBackBtn = 2131099677;
			
			// aapt resource value: 0x7f060014
			public const int barcodeButton = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int buttonLogin = 2131099678;
			
			// aapt resource value: 0x7f060011
			public const int chipButton = 2131099665;
			
			// aapt resource value: 0x7f060022
			public const int contentFrame = 2131099682;
			
			// aapt resource value: 0x7f06001b
			public const int editTextPassword = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int editTextPhoneCommunicationUrl = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int editTextUserId = 2131099673;
			
			// aapt resource value: 0x7f060020
			public const int fetchCallSlipsButton = 2131099680;
			
			// aapt resource value: 0x7f060013
			public const int foundButton = 2131099667;
			
			// aapt resource value: 0x7f06001f
			public const int myList = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int needsLookup = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int nextButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int previousButton = 2131099648;
			
			// aapt resource value: 0x7f060015
			public const int printButton = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int reportFetchButton = 2131099681;
			
			// aapt resource value: 0x7f060003
			public const int scrollView1 = 2131099651;
			
			// aapt resource value: 0x7f06001a
			public const int textView1 = 2131099674;
			
			// aapt resource value: 0x7f060004
			public const int textView2 = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int textView3 = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int textViewSeriesStatement = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int textViewYvi = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int twArea = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int twBarCode = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int twCSnote = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int twCallNumber = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int twDeliveryType = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int twNumberOfDone = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int twSeriesStatement = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int twStatus = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int twTitle = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int twYearVolumeIssue = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CallSlipDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CallSlipShort = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscanneractivitylayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscannerfragmentlayout = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040017
			public const int ExternalNote = 2130968599;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f04000c
			public const int area = 2130968588;
			
			// aapt resource value: 0x7f04000f
			public const int back = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int barcode = 2130968600;
			
			// aapt resource value: 0x7f040002
			public const int callSlipDetails = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int callnumber = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int cnt = 2130968585;
			
			// aapt resource value: 0x7f040019
			public const int fetchcallslips = 2130968601;
			
			// aapt resource value: 0x7f040014
			public const int found = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int missingInternetConnection = 2130968602;
			
			// aapt resource value: 0x7f040012
			public const int needslookup = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int next = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int password = 2130968584;
			
			// aapt resource value: 0x7f04001c
			public const int phoneCommunicationUrl = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int phoneCommunicationUrlText = 2130968605;
			
			// aapt resource value: 0x7f040013
			public const int previous = 2130968595;
			
			// aapt resource value: 0x7f040004
			public const int printslip = 2130968580;
			
			// aapt resource value: 0x7f04001b
			public const int printslipmodel = 2130968603;
			
			// aapt resource value: 0x7f040011
			public const int readBarcode = 2130968593;
			
			// aapt resource value: 0x7f04000a
			public const int readtag = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int releaseunfetcheddialoguemessage = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int releaseunfetcheddialoguetitle = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int reportcollecting = 2130968576;
			
			// aapt resource value: 0x7f04000d
			public const int seriesStatement = 2130968589;
			
			// aapt resource value: 0x7f040015
			public const int status = 2130968597;
			
			// aapt resource value: 0x7f04000b
			public const int title = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int type = 2130968598;
			
			// aapt resource value: 0x7f040007
			public const int username = 2130968583;
			
			// aapt resource value: 0x7f040001
			public const int yearvolumeissue = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int MainBackground = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ViolaBtn = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int ViolaBtnSmall = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
